project_path: "/home/user/RAQUEL"
overwrite: false
log_dir: "logs"

defaults:
  - _self_
  - dataset: tofu
  - llm: default
  - model: default
  - redis: default
  - database: postgres
  - prompt: default
  - paths: default

  # The following overrides are necessary to make the logging colorized.
  - override hydra/job_logging: colorlog_custom

hydra:
  output_subdir: null
  run:
    dir: ${log_dir}
  job_logging:
    handlers:
      console:
        class: logging.StreamHandler
        formatter: colorlog
        stream: ext://sys.stdout
      file:
        class: logging.FileHandler
        filename: ${log_dir}/evaluate.log